openapi: 3.1.0
x-stoplight:
  id: w7teax89iucni
info:
  title: TODO List API
  version: '1.0'
  description: ''
  summary: TODOリストのサンプルAPI
servers:
  - url: 'http://localhost:3000'
paths:
  /tasks:
    get:
      summary: Get All Task
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/Tasks'
        '400':
          $ref: '#/components/responses/400_bad_request'
        '500':
          $ref: '#/components/responses/500_internal_server_error'
      operationId: get-tasks
      x-stoplight:
        id: 5t844oz61ton5
      description: ''
    post:
      summary: Create Task
      operationId: post-tasks
      responses:
        '200':
          $ref: '#/components/responses/Task'
        '400':
          $ref: '#/components/responses/400_bad_request'
        '500':
          $ref: '#/components/responses/500_internal_server_error'
      x-stoplight:
        id: u1a2hle292987
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  x-stoplight:
                    id: 9y9t9n0iu667u
                description:
                  type: string
                  x-stoplight:
                    id: svy2mp749h9yx
              required:
                - title
  '/tasks/{taskId}':
    parameters:
      - schema:
          type: string
        name: taskId
        in: path
        required: true
    get:
      summary: Get Task
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/Task'
        '400':
          $ref: '#/components/responses/400_bad_request'
        '500':
          $ref: '#/components/responses/500_internal_server_error'
      operationId: get-tasks-taskId
      x-stoplight:
        id: gjdtbwk58xr98
      requestBody:
        content: {}
    put:
      summary: Update Task
      operationId: put-tasks-taskId
      responses:
        '200':
          $ref: '#/components/responses/Tasks'
        '400':
          $ref: '#/components/responses/400_bad_request'
        '500':
          $ref: '#/components/responses/500_internal_server_error'
      x-stoplight:
        id: qrsvh6xtl2l8x
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  x-stoplight:
                    id: ot2i1o9oyzxep
                description:
                  type: string
                  x-stoplight:
                    id: 533ahxg7y4y93
              required:
                - title
    delete:
      summary: Delete Task
      operationId: delete-tasks-taskId
      responses:
        '200':
          $ref: '#/components/responses/Task'
        '400':
          $ref: '#/components/responses/400_bad_request'
        '500':
          $ref: '#/components/responses/500_internal_server_error'
      x-stoplight:
        id: az957cb2i9j7y
components:
  schemas:
    User:
      title: User
      type: object
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      x-stoplight:
        id: 637614p0rehrt
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: 4nza98b047rlj
        email:
          type: string
          format: email
          x-stoplight:
            id: relvhjmj9oblz
        username:
          type: string
          x-stoplight:
            id: q24ssai16q7jy
      required:
        - id
        - email
        - username
      description: ''
    Task:
      title: Task
      x-stoplight:
        id: trmssbo748awc
      type: object
      properties:
        id:
          type: string
          x-stoplight:
            id: gbsa7ryjiz8w1
        title:
          type: string
          x-stoplight:
            id: kortu1wqb3tyl
        description:
          type: string
          x-stoplight:
            id: cj93o823vgt83
      required:
        - title
    Error:
      title: Error
      x-stoplight:
        id: 258pkyxirnhsx
      type: object
      properties:
        error:
          type: object
          x-stoplight:
            id: afn7g22of5gyg
          properties:
            message:
              type: string
              x-stoplight:
                id: op9tp0f7ujacl
            code:
              type: integer
              x-stoplight:
                id: aox2dxe7c2duf
  responses:
    400_bad_request:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example 1:
              $ref: '#/components/examples/400_bad_request'
    Tasks:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              tasks:
                type: array
                x-stoplight:
                  id: e0zd5ehbnbwli
                items:
                  $ref: '#/components/schemas/Task'
                  x-stoplight:
                    id: yo9nogsnxxdtm
          examples:
            Example 1:
              $ref: '#/components/examples/Tasks'
    500_internal_server_error:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example 1:
              $ref: '#/components/examples/500_internal_server_error'
    Task:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Task'
          examples:
            Example 1:
              value:
                id: string
                title: string
                description: string
  examples:
    400_bad_request:
      value:
        error:
          message: 400 Bad Request
          code: 400
    Tasks:
      value:
        tasks:
          - id: string
            title: string
            description: string
    500_internal_server_error:
      value:
        error:
          message: 500 Internal Server Error
          code: 500
    Task:
      value:
        id: string
        title: string
        description: string
    Task_request:
      value:
        title: string
        description: string
  requestBodies: {}
